firstapp/urls.py
from django.contrib import admin
from django.urls import path, include

from firstapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.show_home_page, name='home'),
    path('contact-us/', views.show_contactus,name='contactus'),
    path('librarymgmt/', include('library.urls'))
]

library/urls.py
from django.urls import path

from library import views

app_name = 'library'

urlpatterns = [
    # imagine librarymgmt/
    path('index', views.show_login, name='loginpage'),
    path('register', views.show_register, name='registerpage'),
    path('register-user', views.register_user, name='registeruser'),
    path('auth', views.auth, name='authenticate'),
    path('home', views.show_home, name='homepage'),
    path('books/<int:book_id>', views.show_book, name='bookdetails'),
    path('friends', views.get_friends, name='getfriends'),
    path('logout', views.logout, name='logout'),
    path('issue-book/<int:book_id>', views.issue_book, name='issuebook'),
    path('return-book/<int:book_id>', views.return_book, name='returnbook')
]

library/models.py
from django.db import models
from datetime import date

class Publication(models.Model):
    name = models.CharField(max_length=50, null=False)
    ratings = models.IntegerField(null=True)
    # book_set

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100, null=False)
    price = models.FloatField(null=False)
    pages = models.IntegerField(null=True)
    publication = models.ForeignKey(Publication, on_delete=models.CASCADE, default=None)
    count = models.IntegerField(null=False, default=0)
    published_date = models.DateField(null=False, default=date.today())
    # review_set
    # student_set

    def __str__(self):
        return self.title

class Review(models.Model):
    name = models.CharField(max_length=20, null=False)
    description = models.CharField(max_length=500, null=False)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

# Create your models here.
class Student(models.Model):
    username = models.CharField(max_length=40, null=False, unique=True)
    password = models.CharField(max_length=10, null=False)
    country = models.CharField(max_length=3, null=False)

    books_issued = models.ManyToManyField(Book)

library/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=50, label='Username')
    password = forms.CharField(max_length=20, label='Password', widget=forms.PasswordInput)

firstapp/views.py
from django.http import HttpResponse
from django.shortcuts import render
from datetime import datetime

def show_home_page(request):
    # return HttpResponse('<html><body><h2>Welcome to my home page</h2></body></html>')
    now = datetime.time(datetime.now())
    hour = now.hour
    if hour >= 0 and hour < 12:
        message = 'Good morning'
    elif hour >= 12 and hour < 16:
        message = 'Good afternoon'
    else:
        message = 'Good evening'

    context = {
        'message': message
    }

    return render(request, 'home.html', context)

def show_contactus(request):
    # imagine email, mobile coming from the database
    email = 'mehul.chopra.dev@yahoo.com'
    mobile = '987907689'
    addresses = [
        {
            'country': 'India',
            'line1': 'Four Bungalows, Mumbai'
        },
        {
            'country': 'USA',
            'line1': 'Texas'
        },
        {
            'country': 'China',
            'line1': 'sdfdslfnd fdk gdfg df'
        }
    ]

    context = {
        'mobile': mobile,
        'email': email,
        'addresses': addresses
    }
    return render(request, 'contactus.html', context)

library/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect, HttpResponse

from library.models import Student, Book
from library.forms import LoginForm

# Create your views here.

def show_login(request):
    loginform = LoginForm()
    return render(request, 'library/public/login.html', {
        'form': loginform
    })

def show_register(request):
    return render(request, 'library/public/register.html')

def register_user(request):
    username = request.POST['username']
    password = request.POST['password']
    country = request.POST['country']

    s = Student(username=username, password=password, country=country)
    s.save()

    if s.id:
        # successfully registered
        return HttpResponseRedirect(reverse('library:loginpage'))
    else:
        return HttpResponse('Error in registration')

def auth(request):
    form = LoginForm(request.POST)
    if form.is_valid():
        d = form.cleaned_data
        print(d)
    else:
        print('Some field missing')
    # username = request.POST['username']
    # password = request.POST['password']

    '''l = Student.objects.filter(username=username, password=password)
    if len(l):
        # remember the username data
        request.session['username'] = username
        request.session['id'] = l[0].id
        # request.session['student'] = l[0]
        return HttpResponseRedirect(reverse('library:homepage'))
    else:
        return HttpResponseRedirect(reverse('library:loginpage'))'''

def show_home(request):
    if 'username' not in request.session:
        return HttpResponseRedirect(reverse('library:loginpage'))

    # retrieve the data (username) from the session
    username = request.session['username']
    studentid = request.session['id']
    blist = Book.objects.exclude(count=0)
    for book in blist:
        students = book.student_set.filter(pk=studentid)
        if len(students):
            book.alreadyissued = True
        else:
            book.alreadyissued = False

        studentsissued = book.student_set.count()
        if book.count - studentsissued == 0:
            book.canbeissued = False
        else:
            book.canbeissued = True

    context = {
        'booklist': blist,
        'username': username
    }
    return render(request, 'library/private/home.html', context)

def show_book(request, book_id):
    if 'username' not in request.session:
        return HttpResponseRedirect(reverse('library:loginpage'))

    # retrieve the data (username) from the session
    username = request.session['username']
    book = Book.objects.get(pk=book_id)
    context = {
        'book': book,
        'username': username
    }

    return render(request, 'library/private/book.html', context)

def get_friends(request):
    if 'username' not in request.session:
        return HttpResponseRedirect(reverse('library:loginpage'))

    username = request.session['username']
    studentid = request.session['id']
    students = Student.objects.exclude(pk=studentid)
    context = {
        'friends': students,
        'username': username
    }

    return render(request, 'library/private/friends.html', context)

def logout(request):
    request.session.flush()
    return HttpResponseRedirect(reverse('library:loginpage'))

def issue_book(request, book_id):
    if 'username' not in request.session:
        return HttpResponseRedirect(reverse('library:loginpage'))

    studentid = request.session['id']

    student = Student.objects.get(pk=studentid)
    book = Book.objects.get(pk=book_id)

    student.books_issued.add(book)

    return HttpResponseRedirect(reverse('library:homepage'))

def return_book(request, book_id):
    if 'username' not in request.session:
        return HttpResponseRedirect(reverse('library:loginpage'))

    studentid = request.session['id']
    student = Student.objects.get(pk=studentid)
    student.books_issued.remove(book_id)

    return HttpResponseRedirect(reverse('library:homepage'))

# ORM
# OOP -> RDBMS
# class(Model) -> Table
# attributes in class -> Columns
# objects -> Rows

firstapp/templates/contactus.html
{% extends 'master.html' %}

{% block title %}
  Contact us
{% endblock %}

{% block header %}
  Contact USS!
{% endblock %}

{% block menu %}
    <a href="{% url 'home' %}">Home</a>
{% endblock %}

firstapp/templates/home.html
{% extends 'master.html' %}

{% block title %}
  My Home page
{% endblock %}

{% block header %}
  Welcome to my home page<br>
  <i>{{ message }}</i>
{% endblock %}

{% block menu %}
    <a href="{% url 'contactus' %}">Contact Us</a>
{% endblock %}

firstapp/templates/master.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>
      {% block title %}
      {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'styles/app.css' %}">
  </head>
  <body>
    <h2 class="header">
      {% block header %}
      {% endblock %}
    </h2>
    <img class="banner" src="{% static 'images/steveandsteve.jpg' %}" alt="">
    {% block menu %}
    {% endblock %}
    <footer>
      Copyright 2018-19 All Rights Reserved
    </footer>
  </body>
</html>

library/templates/library/master_public.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Welcome to my site</title>
    <link rel="stylesheet" href="{% static 'library/css/app.css' %}">
  </head>
  <body>
    <div class="banner">
      <img src="{% static 'library/images/big_data.jpg' %}" alt="">
    </div>
    <div class="header">
      {% block header %}
      {% endblock %}
    </div>
    <div class="content">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

library/templates/library/private/book.html
{% extends 'library/master_public.html' %}

{% block header %}
  Welcome {{ username }} <br>
  Book Details
{% endblock %}

{% block content %}
  <p>
    Title: {{ book.title }}
  </p>
  <p>
    Pages: {{ book.pages }}
  </p>
  <p>
    Price: {{ book.price }}
  </p>
  <h2>Publication house details</h2>
  <p>
    Name: {{ book.publication.name }}
  </p>
  <p>
    Ratings: {{ book.publication.ratings }}
  </p>
  <h2>Reviews</h2>
  {% if book.review_set.count == 0 %}
    No Reviews Yet!
  {% else %}
    {% for review in book.review_set.all %}
      <div>
        <i>{{ review.name }}</i><br>
        <p>{{ review.description }}</p>
      </div>
    {% endfor %}
  {% endif %}
{% endblock %}

library/templates/library/private/friends.html
{% extends 'library/master_public.html' %}

{% block header %}
  Welcome {{ username }} <br>
{% endblock %}

{% block content %}
  <table border="1">
    <thead>
      <tr>
        <th>Username</th>
        <th>Country</th>
      </tr>
    </thead>
    <tbody>
      {% for friend in friends %}
        <tr>
          <td>{{ friend.username }}</td>
          <td>{{ friend.country }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

library/templates/library/private/home.html
{% extends 'library/master_public.html' %}

{% block header %}
  Welcome {{ username }}
  <a href="{% url 'library:logout' %}">Logout</a>
{% endblock %}

{% block content %}
  <div class="menu">
    <a href="{% url 'library:getfriends' %}">Friends</a>
  </div>
  <table border="1">
    <thead>
      <tr>
        <th>Title</th>
        <th>Price</th>
        <th>Pages</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for book in booklist %}
        <tr>
          <td>{{book.title}}</td>
          <td>{{book.price}}</td>
          <td>{{book.pages}}</td>
          <td><a href="{% url 'library:bookdetails' book.id %}">Details</a></td>
          <td>
            {% if book.alreadyissued %}
              <a href="{% url 'library:returnbook' book.id %}">Return Book</a>
            {% elif book.canbeissued %}
              <a href="{% url 'library:issuebook' book.id %}">Issue Book</a>
            {% else %}
              <label style="color: red">Cannot Issue</label>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}